### ISSUE TITLE
NPM & wiki issues

### ISSUE THREAD

**Issue by snoblenet** [Ephigenia/notable-cli#23]
It appears not to be on NPM at the moment:

```
$ npx notable-cli
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/notable-cli - Not found
npm ERR! 404
npm ERR! 404  'notable-cli@next' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/steven/.npm/_logs/2022-01-19T10_05_05_047Z-debug-0.log
```

Also [the link to the wiki](https://github.com/Ephigenia/notable-cli/blob/main/wiki) is down.

**Comment by Ephigenia** [comment]
yes, project isn't published on npm registry right now, it can only be installed by cloning the repo and us `npm link <directory>` sorry for that.

**Comment by Ephigenia** [comment]
I removed the wiki link from the `README.md` as this is not the current state of it all.

**Comment by Ephigenia** [comment]
@snoblenet It would be nice to see how other users think about the tool. Until now I thought I’m the only one using it.
